# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      - checkout
      # Test
      - run:
          name: "Test"
          command: |
            id
            pwd
      - run:
          name: APT Update
          command: sudo apt update

      # VBox
      - run:
          name: Install VirtualBox
          command: |
            sudo apt install -y virtualbox virtualbox-dkms linux-headers-aws

      # Check VBox Version
      - run:
          name: Check VBox Version
          command: |
            VBoxManage --version

      # Install Vagrant
      - run:
          name: Install Vagrant
          command: |
            curl -O https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_x86_64.deb
            sudo apt install -y ./vagrant_2.2.10_x86_64.deb

      # Check Vagrant Version
      - run:
          name: Check Vagrant Version
          command: |
            vagrant --version

      # Make Vagrant
      - run:
          name: vagrant up
          command: |
            vagrant plugin install vagrant-goodhosts
            vagrant up
